database_use_unix_socket: True

# Create a Galera cluster if more than one database nodes exist
database_create_galera_cluster: "{{ (groups.database | length) > 1 }}"

# File to create when the secure installation process is complete, so it is not attempted again
database_secure_install_marker: /root/.my.cnf

database_log_dir: /var/log/mariadb
database_data_dir: /var/lib/mysql
database_backups_dir: "{{ database_data_dir }}/_backups"

database_systemd_override_dir: "{{ systemd_override_dir }}/mariadb.service.d"
database_systemd_override_file: "{{ database_systemd_override_dir }}/overrides.conf"

database_unix_socket: "{{ database_data_dir }}/mysql.sock"

database_system_user: mysql

database_cluster_name: database_cluster

database_wsrep_slave_threads: "{{ ansible_processor_vcpus * 4 }}"

# The default version value; will be used if Keycloak was not installed yet
keycloak_not_installed_version: 0.0.0
# The maximum Keycloak installed version
keycloak_max_version: "{{ keycloak_not_installed_version }}"
