- become: yes
  block:
    - name: Make sure keycloak has finished booting (and imported users)
      import_tasks: wait_keycloak_started.yml

    - name: Remove add users JSON file if it exists
      command:
        argv: [ "shred", "-zu", "{{ keycloak_add_user_json }}" ]
        removes: "{{ keycloak_add_user_json }}"

    - name: Reset add users JSON file to a default empty file
      copy:
        content: "[]"
        dest: "{{ keycloak_add_user_json }}"
        force: no
        mode: 0660
        owner: "{{ keycloak_system_user }}"
        group: "{{ keycloak_system_user }}"

    - name: Create users created marker file
      copy:
        content: ""
        dest: "{{ keycloak_add_user_marker_file }}"
        mode: 0000
        owner: "{{ keycloak_system_user }}"
        group: "{{ keycloak_system_user }}"
