- become: yes
  block:
    - name: Make sure the keycloak service is running
      systemd:
        name: keycloak
        state: started
        enabled: yes

    - name: Wait until the keycloak service finishes booting
      wait_for:
        path: "{{ keycloak_startup_marker_file }}"
        state: present
        timeout: "{{ service_start_timeout }}"
        msg: "Keycloak did not start after {{ service_start_timeout }} seconds"
