# Amount of memory available for Java service heap space.
java_max_heap_size: "{{ java_max_available_mem }}"
# Minimum heap size. Use the same value as the max to avoid dynamic allocations
java_min_heap_size: "{{ java_max_heap_size }}"
# Maximum size of metaspace
java_max_metaspace_size: "{{ (java_max_heap_size|int / 2)|int }}"
# Metaspace size when a GC will be triggered
java_metaspace_size: "{{ (java_max_metaspace_size|int / 2)|int }}"

# Minimum amount of memory in megabytes we expect a Java service should have to run without issues
# 1024MB base memory + 256MB for 50,000 user sessions
java_min_mem: 1280

java_common_mem_opts: "-Xms{{ java_min_heap_size }}m -Xmx{{ java_max_heap_size }}m -XX:MetaspaceSize={{ java_metaspace_size }}m -XX:MaxMetaspaceSize={{ java_max_metaspace_size }}m -XX:+UseG1GC"

java_version: 21
