keycloak_archive_checksum: sha1:c37d8545e8c0cf761a162922002b0d0d35d36ed8
keycloak_archive_url: "https://github.com/keycloak/keycloak/releases/download/{{ keycloak_version }}/keycloak-{{ keycloak_version }}.tar.gz"
keycloak_install_dir: "/opt/keycloak-{{ keycloak_version }}"
keycloak_tmp_file: "/tmp/keycloak-{{ keycloak_version }}.tar.gz"

keycloak_bin_subdir: "{{ keycloak_install_dir }}/bin"
keycloak_conf_subdir: "{{ keycloak_install_dir }}/conf"
keycloak_data_subdir: "{{ keycloak_install_dir }}/data"
keycloak_log_subdir: "{{ keycloak_data_subdir }}/log"
keycloak_tmp_subdir: "{{ keycloak_data_subdir }}/tmp"
keycloak_providers_subdir: "{{ keycloak_install_dir }}/providers"
keycloak_themes_subdir: "{{ keycloak_install_dir }}/themes"

keycloak_lib_subdir: "{{ keycloak_install_dir }}/lib"
keycloak_quarkus_lib_subdir: "{{ keycloak_lib_subdir }}/quarkus"

keycloak_server_script_file: "{{ keycloak_bin_subdir }}/kc.sh"

keycloak_conf_file: "{{ keycloak_conf_subdir }}/keycloak.conf"
keycloak_infinispan_conf_file: "{{ keycloak_conf_subdir }}/cache-ispn.xml"

infinispan_trusted_certificate_file: "{{ pki_configs.keycloak.trusted_dir }}/infinispan.crt"
database_trusted_certificate_file: "{{ keycloak_conf_subdir }}/database.crt"
keycloak_truststore_file: "{{ keycloak_conf_subdir }}/truststore.jks"
keycloak_keystore_file: "{{ keycloak_conf_subdir }}/application.keystore"

keycloak_keystore_cert_alias: server

keycloak_custom_theme_repo_dir: "/opt/keycloak-custom-theme"
keycloak_custom_theme_src_dir: "{{ keycloak_custom_theme_repo_dir }}/{{ keycloak_custom_theme.path }}/"
keycloak_custom_theme_dir: "{{ keycloak_themes_subdir }}/{{ keycloak_custom_theme.name }}"

keycloak_custom_modules_repo_root_dir: "/opt/keycloak-custom-modules"
keycloak_maven_settings_xml: "{{ keycloak_custom_modules_repo_root_dir }}/settings.xml"
keycloak_maven_repo_dir: "{{ keycloak_custom_modules_repo_root_dir }}/.m2/repository"

keycloak_database_pool_size: 100
keycloak_database_conn_params: "sslMode=verify-full&serverSslCert={{ database_trusted_certificate_file | urlencode }}&enabledSslProtocolSuites=TLSv1.3&enabledSslCipherSuites=TLS_AES_256_GCM_SHA384"
keycloak_database_servers: "{{ cluster_servers.database | product([':%d' % database_listen_port]) | map('join') | join(',') }}"
keycloak_database_conn_url: "jdbc:mariadb://{{ keycloak_database_servers }}/{{ database_config.keycloak.dbname }}?{{ keycloak_database_conn_params }}"

# Use a different port than the standalone Infinispan service to not conflict
# with a dedicated Infinispan service is hosted on the same node as Keycloak
keycloak_infinispan_tcpping_port: "{{ infinispan_tcpping_port + 10 }}"

# Set a three socket connection timeout for HotRod remote stores
keycloak_remote_store_socket_timeout: 180000

keycloak_random_source: /dev/urandom
keycloak_java_opts: "{{ java_common_mem_opts }} -Djava.net.preferIPv4Stack=true -Djava.security.egd=file:{{ keycloak_random_source }} -Dfile.encoding=UTF-8"

keycloak_node_index: "{{ lookup('ansible.utils.index_of', cluster_servers.keycloak, 'eq', inventory_hostname, wantlist=True) | first }}"
keycloak_node_name: "{{ 'k_%d%d' % (cluster_number, keycloak_node_index|int + 1) }}"
keycloak_site_name: "c_{{ cluster_number }}"

# Timeout for first boot. The interval must be enough to allow Keycloak to boot and setup the database and admin user
keycloak_admin_create_timeout: 180s
