- name: Slurp contents of {{ item }} from first server
  become: yes
  run_once: yes
  slurp:
    src: "{{ item }}"
  register: slurped_contents

- name: Copy {{ item }} to remote servers
  become: yes
  copy:
    content: "{{ slurped_contents.content | b64decode }}"
    dest: "{{ item }}"
    mode: "{{ pki_file_mode }}"
    owner: "{{ pki_file_owner }}"
    group: "{{ pki_file_owner }}"
    seuser: system_u
    setype: cert_t
  notify:
    - restart load balancer
