- name: Disable Infinispan service
  become: yes
  block:
    - name: Gather service status information
      service_facts:

    - name: Disable Infinispan service if present
      when: ansible_facts.services['infinispan.service'].status | default('not-found') != 'not-found'
      service:
        name: infinispan
        state: stopped
        enabled: no

    - name: Remove infinispan systemd service file
      file:
        path: "{{ systemd_service_dir }}/infinispan.service"
        state: absent
      notify: systemd reload

- name: Remove or update log file permissions
  become: yes
  block:
    - name: Remove log files
      when: infinispan_remove_logs | default(False) | bool
      file:
        path: "{{ infinispan_server_log_subdir }}"
        state: absent

    - name: Set restrictive log file permissions
      when: not infinispan_remove_logs | default(False) | bool
      block:
        - name: Check if log directory exists
          stat:
            path: "{{ infinispan_server_log_subdir }}"
          register: infinispan_server_log_subdir_stat

        - name: Remove file ACLs from log directory
          when: infinispan_server_log_subdir_stat.stat.exists
          command:
            argv: ["/usr/bin/setfacl", "-b", "{{ infinispan_server_log_subdir }}"]
          changed_when: False

        - name: Only allow root to access log files
          when: infinispan_server_log_subdir_stat.stat.exists
          file:
            path: "{{ infinispan_server_log_subdir }}"
            owner: root
            group: root
            mode: u=rwX,g=,o=
            recurse: yes

- name: Completely remove all files set up for Infinispan and adjacent functionality
  become: yes
  when: infinispan_full_cleanup | default(False) | bool
  block:
    - name: Remove nginx package
      package:
        name: nginx
        state: absent

    - name: Remove nginx configuration files
      file:
        path: /etc/nginx
        state: absent

    - name: Remove Infinispan user
      user:
        name: "{{ infinispan_system_user }}"
        state: absent

    - name: Find Infinispan installation directories
      find:
        paths: "{{ infinispan_install_base_dir }}"
        recurse: no
        patterns: "infinispan-*"
        file_type: directory
      register: infinispan_install_dirs

    - name: Remove Infinispan installation directories
      file:
        path: "{{ item.path }}"
        state: absent
      with_items: "{{ infinispan_install_dirs.files }}"
