- name: restart keycloak
  become: yes
  systemd:
    name: keycloak
    state: restarted
    enabled: yes
  listen: restart java service

- name: delete theme cache
  become: yes
  file:
    path: "{{ keycloak_tmp_subdir }}/kc-gzip-cache"
    state: absent
