rsyslog_default_port: 514
rsyslog_default_proto: udp

rsyslog_max_message_size: 32k

rsyslog_cert_dir: /etc/pki/rsyslog
rsyslog_server_ca_crt_path: "{{ rsyslog_cert_dir }}/server-ca.crt"
rsyslog_client_key_path: "{{ rsyslog_cert_dir }}/client-key.pem"
rsyslog_client_csr_path: "{{ rsyslog_cert_dir }}/client-cert.csr"
rsyslog_client_cert_path: "{{ rsyslog_cert_dir }}/client-cert.pem"

rsyslog_config_file_path: /etc/rsyslog.d/remotelog.conf

rsyslog_input_file_settings:
  read_mode: 0 # line buffering
  severity: info
  facility: local3

regex_backslash: \\
regex_double_backslash: \\\\

rsyslog_journal_configs: "{{ rsyslog_log_configs | selectattr('type', 'eq', 'journal') }}"
rsyslog_program_names_regex: "^({{ rsyslog_journal_configs | map(attribute='program_names') | flatten | map('regex_escape') | map('regex_replace', regex_backslash, regex_double_backslash) | unique | join('|') }})$"
rsyslog_log_file_configs: "{{ rsyslog_log_configs | selectattr('type', 'eq', 'file') }}"
rsyslog_log_file_tags_regex: "^({{ rsyslog_log_file_configs | map(attribute='tag') | flatten | map('regex_escape') | map('regex_replace', regex_backslash, regex_double_backslash) | unique | join('|') }})$"
