rsyslog_default_port: 514
rsyslog_default_proto: udp

rsyslog_cert_dir: /etc/pki/rsyslog
rsyslog_server_ca_crt_path: "{{ rsyslog_cert_dir }}/server-ca.crt"

rsyslog_config_file_path: /etc/rsyslog.d/remotelog.conf
